### ISSUE TITLE
Render incorrectly on old devices

### ISSUE THREAD

**Issue by SAOMDVN** [rive-app/rive-wasm#10]
## Issue
Rive incorrectly renders models on old devices which leads to glitchy animations, shifting body parts,...

## Example
![image](https://user-images.githubusercontent.com/34767287/102848117-9863aa00-4446-11eb-8302-c67c6b33933d.jpeg)

![image](https://user-images.githubusercontent.com/34767287/102848135-a285a880-4446-11eb-89a2-251358be0025.jpeg)

![image](https://user-images.githubusercontent.com/34767287/102848149-ae716a80-4446-11eb-855f-66255d7eefb7.jpeg)

## Device tested
- [x]  iPhone 5S on iOS 12.4.7 (Issue Happened)
- [x]  iPhone 7 Plus on iOS 13.6.1 (No Issue)

**Comment by mjohnsullivan** [comment]
Thanks for the report. We can confirm there are rendering issues on iOS 12 with the runtime. We'll look into it further.

**Comment by mjohnsullivan** [comment]
This is still in our backlog; once we have the next release of the library out, we're going to come back to it.

**Comment by caudetgit** [comment]
at this time, the minimum iOS target version is 14
