### ISSUE TITLE
Huge bundle size 

### ISSUE THREAD

**Issue by JasperSurmont** [rive-app/rive-wasm#101]
Hey!

I'm using Webpack and I'm using rive for just 1 animation in my website. However, when bundling the project I get a parsed size of 240KB, while webpack recommends the bundle to keep below 244KiB. Is there a way to minimize this?

**Comment by mjohnsullivan** [comment]
The reason the bundle is so big is that we include the wasm binary code inside the js bundle to make it simple to use the module. The bundled wasm is base64 encoded, adding another 25% to the size.

I've created a new version of the module: ```dist/rive.lean.dev.js``` that doesn't bundle in the wasm code, dropping the minified side of the js down to around 60kb.

However, you'll need to host the was binary file and give the url to the js module before creating any Rive objects. You can use the ```RuntimeLoader.setWasmUrl()``` to do this.

I've updated the parcel module example (PR is [here](https://github.com/rive-app/rive-wasm/pull/105)) to provide a simple example of how to do this (note that the wasmUrl import is a Parcel-specific thing).

rive-js 0.7.15 is up on npm with the changes.

Let us know if this is useful to you.

**Comment by JasperSurmont** [comment]
Thanks so much! I've never worked with wasm though, could there maybe be an example of how to do this exactly?

**Comment by mjohnsullivan** [comment]
Happy to create an example for you. If you can tell me how your environment is set up (e.g. using react, vue, webpack, etc), then I'll create an example for that.

**Comment by JasperSurmont** [comment]
Thanks! I'm using vue v3 which gets bundled by webpack. I have a single file component, the template is just a canvas.
In the script I import rive and my animation as follows:

```import {Rive, Layout, Alignment, Fit} from 'rive-js';
import Animation from '@/assets/project.riv'
```

and in the `mounted` hook I create rive: 

```
this.rive = new Rive({
      src: Animation,
      canvas: canvas,
      layout: new Layout({fit: Fit.Contain, alignment: Alignment.TopLeft),
      autoplay: true,
})
```

That's all, I hope this is enough information?

**Comment by mjohnsullivan** [comment]
I'm not familiar with Vue 3, but I could modify the Vue 2 example to side load the wasm like this:

```
<template>
  <div>
    <canvas ref="canvas" width="400" height="400"></canvas>
  </div>
</template>

<script>
import { RuntimeLoader, Rive, Layout } from 'rive-js/dist/rive.lean.dev'

RuntimeLoader.setWasmUrl('https://unpkg.com/rive-js/dist/rive.wasm')

export default {
  name: 'Rive',
  props: {
    src: String,
    fit: String,
    alignment: String
  },
  mounted() {
    new Rive({
        canvas: this.$refs.canvas,
        src: this.$props.src,
        layout: new Layout({
            fit: this.$props.fit,
            alignment: this.$props.alignment,
        }),
        autoplay: true
    })
  }
}
</script>
```

Try updating your example to import the lean js with this:

```
import { RuntimeLoader, Rive, Layout } from 'rive-js/dist/rive.lean.dev';
```

Then before you create the Rive object, do this:

```
RuntimeLoader.setWasmUrl('https://unpkg.com/rive-js/dist/rive.wasm')
```

This is serving the wasm from npm's cdn; you can host the file yourself and update the url if you want.

**Comment by mjohnsullivan** [comment]
I think that webpack should tree-shake out the bundled js file that's used by default and include `rive.lean.dev.js` in its place, which is smaller.

**Comment by mjohnsullivan** [comment]
Full example is updated here: https://github.com/rive-app/rive-wasm/pull/106

**Comment by JasperSurmont** [comment]
Thanks so much!

**Comment by JasperSurmont** [comment]
Correct me if I'm wrong, but are you sure it's `0.7.15`? I can only find `0.7.14`

**Comment by JasperSurmont** [comment]
No worries, I tried it and everything worked fine, size dropped like you mentioned to around 60 KiB
