### ISSUE TITLE
[Feature Request] Explore the .riv file

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#13]
## Feature Request
It would be very useful to be able to explore the content of a .riv file once uploaded:

**1. File :** 
- Name of the artboards

**2. Arboard:**
- Name of the animations
- Name of the nodes
- Name of the bones

**3. Node:** 
- Name of the children nodes
- Type of node (group, path, ellipse, ...)
- Their properties (beyond x, y, rotation, scaleX, scaleY)

## Use case
In this animation recorder I load the files from client dynamically, so I've got not many information about the artboards & animations, except the amount of animation in the default artboard.
https://rive-video-recorder.netlify.app/

It would provide a much nicer UX if animations could be named for example.

Thanks for the hard work

**Comment by mjohnsullivan** [comment]
Watch this space; we're working on something very much like this and will have it ready in a week or so.

**Comment by mjohnsullivan** [comment]
https://rive.app/preview/ is our first cut at making a simple tool to explore the animations in a Rive file.

Exploring the lower level stuff is also a great idea; probably should be baked into the api.

**Comment by mjohnsullivan** [comment]
Exposed more of the cpp surface to make listing artboards, state machines, etc. easier and adding in a get contents function to rive-js
