### ISSUE TITLE
Node JS

### ISSUE THREAD

**Issue by SupremeTechnopriest** [rive-app/rive-wasm#142]
Hello, 

Is it possible to use the WASM Runtime with NodeJS?  We are considering switching from Spine and are currently evaluating Rive.  Our animations are all performed server side.  We just need to be able to get the bones local transform to send to our client.  It looks like your JS runtime only works in the client and requires a canvas.  I had an issue open a while ago, but I cant seem to find it anymore.  At that time you said it was something you were working on.  Just wondering if that work ever got done.

Thanks!

**Comment by zplata** [comment]
Sorry for the late reply @SupremeTechnopriest - but you can use an `OffscreenCanvas` too today, instead of a traditional `HTMLCanvasElement`

**Comment by zplata** [comment]
Closing for now, but feel free to re-open if you have troubles with this still!

**Comment by SupremeTechnopriest** [comment]
Thanks for the update! I will give it a try on the next game!
