### ISSUE TITLE
add types in the npm package output

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#247]
Currently `@rive-app/canvas-advanced` & `@rive-app/webgl-advanced` do not provide type definition.
Would be nice to include these [types](https://github.com/rive-app/rive-wasm/blob/master/js/src/rive_advanced.mjs.d.ts) into the output folder & update the [package.json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

Note: the OffscreenCanvas is not supported by Typescript by default anymore (see [issue](https://github.com/microsoft/TypeScript/issues/45745)). You can either remove it or [add a polyfill](https://www.npmjs.com/package/@types/offscreencanvas) to avoid user compiler from breaking.

Thanks.

**Comment by zplata** [comment]
@GrandSchtroumpf We just merged support for types! I'd try with `@rive-app/canvas-advanced` over WebGL for best performance right now and support. And appreciate the tip about `OffscreenCanvas`, we included a types for that in this latest release `1.0.70`!
