### ISSUE TITLE
OffscreenCanvas fails with "rive.requestAnimationFrame"

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#251]
When working with the [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) inside a WebWorker, the method `rive.requestAnimationFrame` throw `window is not defined` (which make sense because there is no `window` object inside a WebWorker).
Using the native `requestAnimationFrame` seems to work though.

**Comment by zplata** [comment]
@GrandSchtroumpf We recently fixed this in 1.0.77 - mind trying it to see if your scenario is addressed by this?
