### ISSUE TITLE
Call delete on objects instanced from WASM.

### ISSUE THREAD

**Issue by luigi-rosso** [rive-app/rive-wasm#269]
Not sure if we're using this anywhere beyond the examples, but in general whenever we new something from the ```rive``` WASM module, we'll need to explicitly delete it when we're done with it.

https://github.com/rive-app/rive-wasm/blob/f2a519d3e5e3bbaef857917067302b11c8373a6c/js/src/utils/registerTouchInteractions.js#L34-L36

We should be calling ```invertedMatrix.delete();``` and ```canvasCoordinatesVector.delete();``` at some point!

**Comment by zplata** [comment]
Addressed in https://github.com/rive-app/rive-wasm/pull/273
