### ISSUE TITLE
Pointer exit doesn't work in rive-wasm

### ISSUE THREAD

**Issue by pa5aribu** [rive-app/rive-wasm#277]
The pointer exit doesn't seem to work when I imported rive animation to my website. The pointer exit works fine on rive editor. Please check the attached videos.

https://user-images.githubusercontent.com/3829210/201787509-2d375df9-fd39-47b3-9158-a9c14830a906.mov

https://user-images.githubusercontent.com/3829210/201787523-e51c6d41-efeb-4b5d-9e03-f4fcdec70584.mov

Code I use
<img width="280" alt="Screen Shot 2022-11-15 at 06 15 34" src="https://user-images.githubusercontent.com/3829210/201787741-d8c568d6-4380-45be-afc8-f54ea612ad23.png">

**Comment by zplata** [comment]
Hey @pa5aribu , do you have a backup `.rev` file to share for this to try and reproduce? We've tested the recent change linked against pointer exit and it seems to still work ok but perhaps we can try and see if there's a case we're missing.

**Comment by zplata** [comment]
@pa5aribu - do you still have this issue?
