### ISSUE TITLE
Add types for @rive-app/webgl-advanced

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#287]
Currently the `@rive-app/canvas-advanced` has [types](https://github.com/rive-app/rive-wasm/blob/master/js/npm/canvas_advanced/package.json#L29), but not the `@rive-app/webgl-advanced` one.
It would be nice to have them as it breaks build in some strict typescript environments

**Comment by zplata** [comment]
Interesting! We'll look into it, thanks
