### ISSUE TITLE
[Discussion] Typescript repo

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#30]
Following [comment](https://github.com/rive-app/rive-wasm/pull/28#issuecomment-775626903) from @mjohnsullivan I would like to offer some recommendations : 

## Monorepo with nx
With `rive-js` the project is now a monorepo with a graph dependency. This is possible that more libraries will come in the future (`rive-webgl`, ...) and you'll need a tool to manage the build system.

For that, I would blindly recommend [nx workspace](https://nx.dev/). It'll take care of all the config (linter, typescript config, test, dependencies tree, build, ...) and support both libs & apps (convenient for real world examples).

**Quick setup** :
1. Setup the repo
```
npx create-nx-workspace rive
> oss
> no
```
2. Setup one lib:
```
cd rive
npm install -D @nrwl/node
nx generate @nrwl/node:library --name=wasm --importPath=rive-wasm --buildable --publishable --strict
```
This will create a folder "packages/wasm" with all the config require to start the lib in typescript (--strict is for strict typescript types).

3. Build the lib:
```
npx nx build wasm
```

I've got this project for example, if you want to have a look (15 inter-dependent libs + 5 examples apps): https://github.com/ethereum/remix-plugin

**Comment by mjohnsullivan** [comment]
Nice; I've not heard of nx before; I'll take a look at it.

**Comment by GrandSchtroumpf** [comment]
I've played a little with nx so you could see how a nx monorepo for rive would look like, you can find the result here : 
https://github.com/GrandSchtroumpf/rive-monorepo
I've commented the process along the way in the readme if you want to have a look. Happy to provide more details if you're interested 😉.

**Comment by mjohnsullivan** [comment]
Excellent! Thanks for the link; I'll definitely take a look.
