### ISSUE TITLE
@rive-app/webgl - Uncaught TypeError: _a.delete is not a function

### ISSUE THREAD

**Issue by Andy1210** [rive-app/rive-wasm#333]
### Description
the clear() function is not working on the rive instance as it seems it doesn't have the delete function when using the @rive-app/react-webgl package.

### Provide a Repro
https://codesandbox.io/s/rive-react-sandbox-m8yz2i 
just click on the Cleanup button and you will see the error straight away

### Expected behavior
cleanup shouldn't throw error and work normally

**Comment by zplata** [comment]
Thanks for the repro and report; definitely looks off! We'll take a look here and update when this is fixed

**Comment by zplata** [comment]
Closing as this is resolved in `2.7.4`. Feel free to re-open this if you still have issues. Thanks again for reporting!
