### ISSUE TITLE
Why rive trying to call webgl2 and webgl in canvas-lite package?

### ISSUE THREAD

**Issue by smnfox** [rive-app/rive-wasm#355]
### Description
I use canvas-lite package and when creating new Rive instance at first it trying to use webgl context

### Provide a Repro
Small example https://codepen.io/Nadezhda-Trenogina/pen/yLWJvoK?editors=1111
Click "run" and alert will be shown with called context type. And there is webgl2 and webgl, only in the end will be 2d

### Expected behavior
For package canvas-lite i expected only 2d context to be used

#### Screenshots
<img width="459" alt="image" src="https://github.com/rive-app/rive-wasm/assets/31614392/f3bb70f4-df54-49d0-9e5a-81b28cc36ff8">

### Browser & Versions (please complete the following information)
- Browser: Chrome 123
- OS: macOS 13.1

#### Additional context
Reproduced on every my device. I saw this behaviour when tried to debug problem on old android device, that doesn`t work correctly with webgl and immediately shows error instead of animation. Now i am confused why it works this way

If described behavior is correct and there is no bug, then maybe i can somehow choose what context i want to use to avoid webgl?

**Comment by luckydye** [comment]
I also ran into this, had to downgrade to [2.7.8](https://www.npmjs.com/package/@rive-app/canvas-advanced/v/2.7.8). Appears to be happening from 2.7.9 up.

**Comment by HayesGordon** [comment]
Hi all, Rive web uses WebGL to draw [image meshes](https://rive.app/community/doc/meshes/docdJwZKih2V) for canvas.

Closing this issue as it's functionality we depend on.
