### ISSUE TITLE
Issue with fill-rule evenodd

### ISSUE THREAD

**Issue by TECHNOFAB11** [rive-app/rive-wasm#39]
Ive used https://covector.github.io/rive-png-renderer/ and noticed that the output wasnt right. It uses rive-wasm so it probably is an issue with that.
The part which uses fill-rule: evenodd doesnt render correctly.
Example file:
[example.riv.zip](https://github.com/rive-app/rive-wasm/files/5989025/example.riv.zip)

The issue is that the part that should be "cut out" isnt cut out. So in the end the whole scene/screen is green instead of transparent in the example

**Comment by mjohnsullivan** [comment]
Thanks for reporting this and sending the example file. We'r taking a look and will respond shortly.

**Comment by mjohnsullivan** [comment]
We found an issue with the Wasm renderer and fixed that up.

If you grab either master or 0.6.12 from npm, that should sort the problem out.
