### ISSUE TITLE
[SSR] window is undefined

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#45]
With server side rendering I've got `window is undefined` because I try to access the `Rive` object from the global scope in a server.
To solve that the best would be to export Rive as a module instead of injecting it into the window object.

**Comment by mjohnsullivan** [comment]
Currently it's exported both as a module and attached to the global scope for those who want to directly embed into a web page with a script tag. In the JS library, the relevant code in rive.js is:

```js
// Exports needed to expose these for some reason as ES2015 export not working
if (typeof exports !== 'undefined') {
  exports.Rive = Rive;
  exports.Alignment = Alignment;
  exports.Fit = Fit;
  exports.Layout = Layout;
}

// Tie these to global/window for use directly in browser
if (typeof global !== 'undefined') {
  global.Rive = Rive;
  global.Rive.Alignment = Alignment;
  global.Rive.Fit = Fit;
  global.Rive.Layout = Layout;
} else if (typeof window !== 'undefined') {
  window.Rive = Rive;
  window.Rive.Alignment = Alignment;
  window.Rive.Fit = Fit;
  window.Rive.Layout = Layout;
}
```

In the Wasm library (which is auto-generated by Enscriptem), it's:

```js
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Rive;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Rive; });
    else if (typeof exports === 'object')
      exports["Rive"] = Rive;
    
```

Always open to doing this differently if there's a better way.

**Comment by GrandSchtroumpf** [comment]
I see, here you're using commons export system. Which has been introduced by nodejs at a time when es6 module wasn't a thing yet. Now browsers & webworker support natively the es6 module which provides a unified way of exporting / importing libraries.
Commonjs export is usually used to have code compatible with old version of nodejs. As rive-canvas requires a HtmlCanvasElement it quite safe to use es6 module instead of commonjs.
I think es6 module could be a single export target for all use case of rive-canvas (pure html or web framework). You can the [mdn documentation here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html).

The only usecase that es6 module wouldn't cover is if someone wants to run rive-canvas with a mock version of the HtmlCanvasElement (with jsdom for example) in an old node version (es6 module are native to nodejs since v13).

**Comment by mjohnsullivan** [comment]
The Wasm JS code is auto-generated; can you think of a way that will let us wrap/define this for use in a clean es6 module way? The reason we stuck with commons was do to the limitations of the Emscripten generated code.

**Comment by GrandSchtroumpf** [comment]
There are two directions : 

### Automatically generate the wasm bindings with `em++`
- The advantage is that the binding always match the C++ API in `binding.cpp`.
- The problem is that you are limited by the file exported.
- A solution would be to find a compiler/configuration that matches the expected output (typescript / esm). [nbind](https://github.com/charto/nbind) could be a candidate but it hasn't been updated since 2years...

### Only generate the wasm file and do the bindings by hand
- The advantage is that you can see the wasm file as an "asset" file, and you can design your own API around.
- The problem is that you need to make sure that C++ & JS bindings are always in sync.

For me solution 1 is better in the long run because you automate the building process from c++ to the end API. But it requires to time & research. I tend to go for the second option for a short-middle term solution as it provides more flexibility & understanding of what's going on.
There are always room for automation, but I think it should not become a limitation.

I think something like that could do most of the job. The tricky part is the binding :
```typescript
export async function getModule(wasmUrl: string) {
  if ('compileStreaming' in WebAssembly) {
    return WebAssembly.compileStreaming(fetch(wasmUrl));
  } else {
    const response = await fetch(wasmUrl);
    return response.arrayBuffer();
  }
}
export async function loadRive(wasmUrl: string): Promise<Rive> {
  const module = await getModule(wasmUrl);
  const importObject = { }; // binding here
  const instance = await WebAssembly.instantiate(module, importObject);
  return instance.exports;
}
```
Here is the documentation about how to [import wasm into Javascript](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API).

**Comment by mjohnsullivan** [comment]
We have a new way of packaging the library with Webpack; it's on this branch: https://github.com/rive-app/rive-wasm/tree/move_rive_typescript

**Comment by mjohnsullivan** [comment]
There's now two builds of the library:

rive.min.js which is aimed at being browser friendly and directly embedded by a script tag.
rive.dev.js which supports ES6 modules and is not minified, aimed at use through npm fro React, Next, etc. and be friendlier for SSR.

**Comment by mjohnsullivan** [comment]
Does the new dual build system fix this issue for you?

**Comment by GrandSchtroumpf** [comment]
I installed latest version of rive-canvas (0.7.1) and it seems that it is still exported as Commonjs. Is rive-canvas published as a ES module or only rive-js ?

**Comment by mjohnsullivan** [comment]
Ah, rive-canvas is; the changes we made are in Rive.js, which has both simple embeddable script and the ES6 versions.

rive-canvas is auto-generated and we don't have immediate plans to change that, but we're always looking for ways to improve this.

**Comment by GrandSchtroumpf** [comment]
Maybe a quick solution that wouldn't required to change auto-generation would be to change to [target output of emscripten](https://github.com/rive-app/rive-wasm/blob/master/wasm/build-wasm.sh#L14) to ES6 : 
```
-o $OUTPUT_DIR/rive.mjs \
```
Here is the [documentation](https://emscripten.org/docs/tools_reference/emcc.html?highlight=es6).
I don't know how it's going to behave with Embind, but this could be a quick win :).

Else, if there is no shot term plan for `rive-canvas`, let's close this issue.

**Comment by mjohnsullivan** [comment]
Latest PR generates both a vanilla and ES6 module version of the package.
