### ISSUE TITLE
Device Pixel Ratio and Retina Support?

### ISSUE THREAD

**Issue by getflourish** [rive-app/rive-wasm#48]
I have a feeling that the web API is not taking into account the device pixel ratio. When I try the demo, the animation appears blurry on my retina Mac. This is also noticeable on the rive.app website.

**Potential Fix**
A simple fix would be to double the canvas context and then downscale the canvas itself. I think the API could somehow do this behind the scenes.

**Workaround**
What I can do right now is to set a rather large size on the canvas and then use CSS transforms to downscale it. But this comes with other issues. 

CodePen:
Here you can visually compare the rendering quality / edges of a an unscaled and scaled canvas.
https://codepen.io/getflourish/pen/XWNOojM

Visual Comparison: 
scale: 1.0 (left) vs scale: 0.5 (right)

<img width="813" alt="image" src="https://user-images.githubusercontent.com/183989/111031213-9fc39f80-8406-11eb-9007-b5d162fd7a41.png">

**Comment by mjohnsullivan** [comment]
Thanks for highlighting this; we're seeing the same thing ourselves and are working on a fix for this in the runtime.

**Comment by zplata** [comment]
@getflourish You can `onLoad` of the Rive instance when created, call `.resizeDrawingSurfaceToCanvas()` to correctly set the width/height attributes accordingly with `devicePixelRatio` taken into account.

More here: https://help.rive.app/runtimes/overview/web-js/faq#why-is-my-animation-blurry-at-runtime

**Comment by getflourish** [comment]
Thanks!

**Comment by inigoLlamosasConneqtech** [comment]
Hello. I am having the same problem while on an angular app. Unfortunately, I cannot find Rive object on RiveModule via ng-rive. So I cannot call .resizeDrawingSurfaceToCanvas(). Is there any workaround this? Am I missing something? Thanks.

**Comment by folsze** [comment]
I am also experiencing this issue with Angular on my MacOS. Is there any advice what to do for pixelated graphics with ng-rive ?
