### ISSUE TITLE
Unable to load .riv files with Rollup

### ISSUE THREAD

**Issue by msobie** [rive-app/rive-wasm#49]
Are there any examples of using Rive with Rollup?

I am trying to use Rive with React (Vite) and Svelte. Both use rollup to bundle, and are showing similar errors that prevent .riv files from loading.

[Here is a sandbox for Svelte](https://codesandbox.io/s/svelte-rive-test-sjcx5). If you open the app in New Window and inspect the dev tools, it fails with `Cannot read property 'getContext' of null`. When running a Vite app, it fails with `ReferenceError: color is not defined`. Both errors are coming from rive.js (v0.0.4).

**Comment by msobie** [comment]
I went ahead and created an [additional sandbox for Vite](https://codesandbox.io/s/vite-rive-test-99krk). As mentioned in my first comment, if you open the app in New Window and inspect dev tools, you will see `ReferenceError: color is not defined`.

**Comment by mjohnsullivan** [comment]
We've not used this with Rollup; we use Webpack which should be working fine.

We'll take a look at Rollup and see what might be happening.

**Comment by mjohnsullivan** [comment]
We've heavily refactored how the package is being packed; once this is close to being released, we'll test it with Rollup to see if it's helped the problem.

**Comment by mjohnsullivan** [comment]
Looks like the new packing is working; I forked your sandbox and updated to the new API:

https://codesandbox.io/s/svelte-rive-test-forked-kx23t?file=/public/index.html

**Comment by mjohnsullivan** [comment]
This might not be the best way though; there's now also rive.dev.js, which is ES6 friendly and designed to be imported through npm for use in React, Next, etc.

Let me know how you get on with 0.1.0 beta.

**Comment by msobie** [comment]
Appreciate the update. Do you mind clarifying on "might not be the best way"? Not sure how I should go about adding the new API to my project.

**Comment by msobie** [comment]
@mjohnsullivan I went ahead and tried 0.1.0 beta (imported from unpkg) in a local Svelte app and it fails with: `wasm streaming compile failed: LinkError: WebAssembly.instantiate(): table import 40 is smaller than initial 900, got 773`.

Feel free to close this issue as you see fit. I plan to experiment with the web API once it reaches a stable version. I'm sure most of the problems I am having will be resolved by then, so not sure if this issue is worth keeping open with the API being in constant flux. Thanks again for the help.

**Comment by mjohnsullivan** [comment]
There's a problem with the older packages that always pulled the latest wasm instead of the compatible one.

For v6 files, please use v0.6.1, which should do the right thing.
For v7, please use the latest build (currently v0.7.2).

**Comment by mjohnsullivan** [comment]
And this was a very useful issue to highlight some of the issues folk are having; thanks for doing this.

**Comment by sosaucily** [comment]
The 0.7.2 release just yesterday fixed this issue for me! Big thanks, works well now with Svelte / Rollup, although it was a bit tricky. Happy to share some example code if it would be helpful

**Comment by mjohnsullivan** [comment]
Excellent! If you could share some example code, that'd be great. We're in the process of changing up our pipeline for building the package to make it easier to use in web frameworks and I'd love see what hoops you had to jump through so we can try and improve matters.
