### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by justinalexandershaw** [rive-app/rive-wasm#51]
If you go on airplane mode or turn off your wifi, the Rive animation no longer works. I would like to be able to package everything that I need to display my animations when I build my site so that when the user is offline, my web app still works.

**Comment by mjohnsullivan** [comment]
Rive uses standard http to download its Wasm runtime and Rive file(s). The browser will typically cache these assets, but re-opening or refreshing the browser will obviously cause things to break.

To have a real offline experience through a browser, you might want to look at service workers where you can handle downloading and then caching any assets your web page uses.

**Comment by justinalexandershaw** [comment]
Oh interesting. I downloaded the RIV file as an asset locally and I have caching set up. I thought about setting up a service worker but it would be great to support offline Rive animations without them (so long as I have all the right components cached on the device).

Thanks for the fast reply! Super cool project :)

Justin

**Comment by mjohnsullivan** [comment]
You're welcome! Note that the library uses Wasm under the hood, so you'll need to check that rive.wasm (https://unpkg.com/rive-js/dist/rive.wasm) is also being cached.

We have a pure (i.e. non-wasm) version of the js, but haven't put that up on npm (yet); it adds a bit of additional size to the overall download.

**Comment by sguergachi** [comment]
@mjohnsullivan do you know if using the setWasmUrl() to use a locally hosted version of the wasm file will work in an offline scenario?
