### ISSUE TITLE
Wordpress integration

### ISSUE THREAD

**Issue by geetesh07** [rive-app/rive-wasm#52]
I have no experience in coding please help me with wordpress integration of this api and the resources i designed

**Comment by mjohnsullivan** [comment]
I have no direct experience with WordPress, but I imagine there's a way to embed Javascript into a WordPress page. 

You'll need to host your Rive file somewhere, and then embed a HTML snippet like the following into your page:

```html
<canvas id="canvas"></canvas>

<script src="https://unpkg.com/rive-js@0.0.4/dist/rive.js"></script>
<script src="https://unpkg.com/rive-js@0.0.4/dist/rive.js"></script>
<script>
    new Rive({
        src: <url to your rive file>,
        canvas: document.getElementById('canvas'),
        autoplay: true,
    });
</script>
```

You'll probably need to tailor this to what WordPress expects.

**Comment by geetesh07** [comment]
i used elementor and selected custom HTML and it worked :)

**Comment by mjohnsullivan** [comment]
Excellent!
