### ISSUE TITLE
BindingError with ParcelJS and ReactJS

### ISSUE THREAD

**Issue by MrEmii** [rive-app/rive-wasm#55]
When I try to load the animation I get an error, out of frustration I tried in codesandbox and it worked perfectly, they have the same packages but it still doesn't work, what can I do?

Sandbox: https://codesandbox.io/s/compassionate-darkness-7cxw1?file=/src/App.js

Error: `{
    "name": "BindingError",
    "message": "Cannot pass non-string to std::string",
    "stack": "BindingError: Cannot pass non-string to std::string\n    at BindingError.<anonymous> (http://localhost:1234/index.3fafb3e2.js:29078:21)\n    at new BindingError (eval at Ft (http://localhost:1234/index.3fafb3e2.js:29035:30), <anonymous>:4:34)\n    at Jt (http://localhost:1234/index.3fafb3e2.js:29119:17)\n    at Object.toWireType (http://localhost:1234/index.3fafb3e2.js:29863:107)\n    at Artboard$animation [as animation] (eval at ne (http://localhost:1234/index.3fafb3e2.js:29525:34), <anonymous>:8:26)\n    at u._addAnimations (http://localhost:1234/index.3fafb3e2.js:30477:35)\n    at u.play (http://localhost:1234/index.3fafb3e2.js:30554:21)\n    at Object.action (http://localhost:1234/index.3fafb3e2.js:30428:13)\n    at u._loadQueue (http://localhost:1234/index.3fafb3e2.js:30463:72)\n    at u._loadQueue (http://localhost:1234/index.3fafb3e2.js:30463:50)"
}`

**Comment by mjohnsullivan** [comment]
We've changed how we're bundling up the rive-js package which should fix this problem.

Please see https://codesandbox.io/s/exciting-leftpad-sv7jr for a working example.
