### ISSUE TITLE
Incompatible wasm version pulled

### ISSUE THREAD

**Issue by coreystanford** [rive-app/rive-wasm#57]
rive-js version: 0.0.4
Editor version: 0.5.38

The wasm file pulled is https://unpkg.com/rive-js@0.7.1/dist/rive.wasm (latest).

Upgrading to 0.7.1 isn't an option right now because the editor exports .riv files in v6.3, not v7, which is noted as being necessary for 0.7.1 in the changelog.

The incompatible wasm file results in the following error:
`Uncaught (in promise) RuntimeError: abort(LinkError: WebAssembly.instantiate(): table import 40 is smaller than initial 900, got 773). Build with -s ASSERTIONS=1 for more info.`

**Comment by mjohnsullivan** [comment]
Unfortunately the older versions of the runtime puled the latest wasm, not the compatible one.

We have done a v6 build that should do the right thing: 0.6.1. Can you try that?

**Comment by coreystanford** [comment]
I bumped to the latest version now that the compatible Editor has rolled out. Thanks!
