### ISSUE TITLE
workStart / workEnd should be null or undefined

### ISSUE THREAD

**Issue by GrandSchtroumpf** [rive-app/rive-wasm#60]
Previously `workStart` & `workEnd` was 0 when work area wasn't specified, now it looks like it returns `-1`.
Best would be to set it to undefined or null when not defined so we can do 
```typescript
const start = animation.workStart ?? 0;
const end = animation.workEnd ?? animation.duration;
```
Maybe also add a comment in changelog, readme or in the d.ts : 
```typescript
/** Start of the work area. If no work area then -1 */
workStart: number;
```

**Comment by mjohnsullivan** [comment]
The change happened on the cpp side and the js is being auto-generated. Our new default value for undefined uints is -1.

There is the enableWorkArea boolean flag in the cpp; I can expose that in Wasm so you can use it to work out if there's a work area for the animation.

Would that work?

**Comment by GrandSchtroumpf** [comment]
That makes things clearer indeed. Thanks.
