### ISSUE TITLE
is there any wey to transform .flr to .riv

### ISSUE THREAD

**Issue by KuuBee** [rive-app/rive-wasm#7]
hi, Im first use Rive.
I try to run a demo in js and I find Rive1 file is .flr but Rive2 file is .riv
Is there any way to transform them or the engine can run in Compatibility mode？

**Comment by mjohnsullivan** [comment]
At present this runtime only supports Rive 2 files. We are in the process of updating the Rive 2 editor to be able to import Rive 1 files to convert them to Rive 2.

**Comment by KuuBee** [comment]
Hum,ok. I will waiting for it and thank you.
I will close this issue.

**Comment by neurowave** [comment]
Give this a shot @KuuBee. Note that some features are not supported yet, please refer to the details in the link! https://help.rive.app/getting-started/faq-1/importing-rive-1-files

**Comment by hiruthic2002** [comment]
Hey, I have a wired problem, I am only getting the .riv file, not the .flr file. I am not getting the option to export its only showing the option to download which downloads as a .riv file. Any idea what am I doing wrong
![image](https://user-images.githubusercontent.com/56349092/110964440-33e72580-8379-11eb-9dd5-3bea2089f3d6.png)

**Comment by neurowave** [comment]
Hi, the new Rive exports .riv files not .flr (that was the old version, formerly Flare). 

What documentation are you looking at? You’re probably looking at something that’s out of date!

Check out our guides and resources for the new Rive at https://rive.app/resources

**Comment by iamaryanshandilya** [comment]
Hey,  I have a .flr file and I need to convert it to .riv. As per the link given by @neurowave, I tried to go to https://flare.rive.app/ but there it shows that registrations will not be done and I cannot import the file in the new editor by drag and drop. So, I shall be glad if I could get some help.
[https://github.com/FilledStacks/flutter-tutorials/blob/master/002-flutter-flare-pt1/01-start/assets/button-animation.flr] is the file I am trying to convert.

**Comment by neurowave** [comment]
Hey @iamaryanshandilya not a silly question! You need to contact the creator (FilledStacks) of that file and ask them to give you the source for that file (should be a .flr2d file). Then you can try to import it into the new editor, though keep in mind that not all the old features are supported yet. https://help.rive.app/getting-started/faq-1/importing-rive-1-files

**Comment by qq326646683** [comment]
I follow this:https://help.rive.app/getting-started/faq-1/importing-rive-1-files ,but it can't success

**Comment by killabit** [comment]
Well we are in 2022 and still no Rive support for there original format.. What a cluster fudge...

**Comment by neurowave** [comment]
> Well we are in 2022 and still no Rive support for there original format.. What a cluster fudge...

There has been support for converting the source file (.fl2rd) to the new editor since 2020, as my message from Dec 2, 2020 above states. The original issue is about converting the exported format (.flr) to the new exported format (.riv) which was never planned to be supported. You need the original source to import it into the new editor. The old export format (.flr) was purely intended for runtime and has no editor data associated to it. It cannot be imported into the new editor.

**Comment by sinhpn92** [comment]
Hummm. It's cannot import from .fl2rd file. I tried and It's throw error cannot upload file.

**Comment by umberto-sonnino** [comment]
> Hummm. It's cannot import from .fl2rd file. I tried and It's throw error cannot upload file.

@sinhpn92 could you share the the Flare file that's failing for you? 
Either here or at support@rive.app
