### ISSUE TITLE
Layers hidden in editor display in runtime

### ISSUE THREAD

**Issue by alxgibsn** [rive-app/rive-wasm#77]
Layers toggled off via the eye icon in the editor hierarchy are visible in the runtime.

I guess this could be purposeful, but I've found it a tricky one to understand why an animation playing in a runtime doesn't look that same as that in the editor.

**Comment by luigi-rosso** [comment]
That's a buuuuuuuuug.

**Comment by mjohnsullivan** [comment]
Probably in the cpp?
