### ISSUE TITLE
wont show anything

### ISSUE THREAD

**Issue by arman8415** [rive-app/rive-wasm#9]
Hello im trying to play my animation in web but i dont know why it doesn't work even i followed everything in https://blog.rive.app/rives-web-runtime/... 

i used my .riv file with "loop" animation name.
i used the rive canvas from here https://www.npmjs.com/package/rive-canvas
i also tried the cdn
still doesn't work :(

**Comment by mjohnsullivan** [comment]
Can you post example code so we can help with this?

**Comment by arman8415** [comment]
> Can you post example code so we can help with this?

I just followed the steps from here https://blog.rive.app/rives-web-runtime/
i also installed rive-canvas... 

im trying to put my animations in angular web app but i cant make it work

<script>
  ; (function () {
    // first, instantiate the Rive engine and load the WASM file(s)
    Rive({
      locateFile: (file) => 'https://unpkg.com/rive-canvas@0.0.10/' + file,
    }).then((rive) => {
      const req = new Request('myanimation.riv');
      fetch(req).then((res) => {
        return res.arrayBuffer();
      }).then((buf) => {
        const file = rive.load(new Uint8Array(buf));
        const artboard = file.defaultArtboard();
        const vibrationAnim = artboard.animation('vibration');
        const vibrationInstance = new rive.LinearAnimationInstance(vibrationAnim);
        const canvas = document.getElementById('riveCanvas');
        const ctx = canvas.getContext('2d');
        const renderer = new rive.CanvasRenderer(ctx);
        artboard.advance(0);
        ctx.save();
        renderer.align(rive.Fit.contain, rive.Alignment.center, {
          minX: 0,
          minY: 0,
          maxX: canvas.width,
          maxY: canvas.height
        }, artboard.bounds);
        artboard.draw(renderer);
        ctx.restore();
        let lastTime = 0;
        function draw(time) {
          if (!lastTime) {
            lastTime = time;
          }
          const elapsedTime = (time - lastTime) / 1000;
          lastTime = time;

          vibrationInstance.advance(elapsedTime);
          vibrationInstance.apply(artboard, 1.0);
          artboard.advance(elapsedTime);
          ctx.clearRect(0, 0, canvas.width, canvas.height);
          ctx.save();
          renderer.align(rive.Fit.contain, rive.Alignment.center, {
            minX: 0,
            minY: 0,
            maxX: canvas.width,
            maxY: canvas.height
          }, artboard.bounds);
          artboard.draw(renderer);
          ctx.restore();

          requestAnimationFrame(draw);
        }
        requestAnimationFrame(draw);
      });
    });
  })();
</script>

**Comment by mjohnsullivan** [comment]
I'm not an expert on Angular, but someone made a Rive Angular module that might help: https://github.com/dappsnation/ng-rive

**Comment by mjohnsullivan** [comment]
Checking in to see if the prior link was useful?

**Comment by mjohnsullivan** [comment]
Closing this for the moment, but please let us know if you're still having problems.
